/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/femaleBot.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Beta_Surface: THREE.Mesh
    Beta_Joints: THREE.Mesh
  }
  materials: {
    Beta_HighLimbsGeoSG3: THREE.MeshStandardMaterial
    Beta_Joints_MAT1: THREE.MeshStandardMaterial
  }
}

export function FemaleModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/femaleBot.glb') as GLTFResult
  console.log(nodes);
  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
      <mesh geometry={nodes.Beta_Surface.geometry} material={materials.Beta_HighLimbsGeoSG3} />
      <mesh geometry={nodes.Beta_Joints.geometry} material={materials.Beta_Joints_MAT1} />
    </group>
  )
}

useGLTF.preload('/femaleBot.glb')
